FROM python:3.12-slim AS build 

COPY requirements.txt ./

RUN python3 -m pip install --upgrade pip wheel && \
    pip wheel --no-cache-dir --wheel-dir /wheels -r requirements.txt


FROM python:3.12-slim 

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app 

COPY --from=build /wheels /wheels

RUN apt update -y && \
    apt install --no-install-recommends -y curl && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

RUN pip install --no-cache-dir --no-index --find-links /wheels -r requirements.txt

COPY . ./

EXPOSE 8000

ENTRYPOINT ["./entrypoint.sh"]

